using System.Collections;
using System.Collections.Generic;
using System.Security.AccessControl;
using UnityEngine;

public class Sliceable : MonoBehaviour
{
    [SerializeField]
    private bool _isSolid = true;

    [SerializeField]
    private bool _reverseWindTriangles = false;

    [SerializeField]
    private bool _useGravity = false;

    [SerializeField]
    private bool _shareVertices = false;

    [SerializeField]
    private bool _smoothVertices = false;

    public bool IsSolid
    {
        get
        {
            return _isSolid;
        }
        set
        {
            _isSolid = value;
        }
    }

    public bool ReverseWireTriangles
    {
        get
        {
            return _reverseWindTriangles;
        }
        set
        {
            _reverseWindTriangles = value;
        }
    }

    public bool UseGravity 
    {
        get
        {
            return _useGravity;
        }
        set
        {
            _useGravity = value;
        }
    }

    public bool ShareVertices 
    {
        get
        {
            return _shareVertices;
        }
        set
        {
            _shareVertices = value;
        }
    }

    public bool SmoothVertices 
    {
        get
        {
            return _smoothVertices;
        }
        set
        {
            _smoothVertices = value;
        }
    }

    public void Update()
    {
        if (gameObject.transform.parent != null)
        {
            if (gameObject.transform.parent.name == "Interactables")
            {
                if (this.GetComponent<BoxCollider>() != null)
                {
                    this.GetComponent<BoxCollider>().enabled = true;
                }
                if (this.GetComponent<MeshCollider>() != null)
                {
                    this.GetComponent<MeshCollider>().enabled = true;
                }
            }
        } else
            this.gameObject.transform.SetParent(GameObject.Find("Interactables").transform);
    }
}
